AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Code Pipeline Slack Notifier

Parameters:
  SlackBotUserOAuthAccessToken:
    MinLength: 1
    Type: String
    NoEcho: True
  SlackChannel:
    Type: String
    MinLength: 1
    Default: builds
  SlackAppId:
    MinLength: 1
    Type: String

Resources:
  Notifier:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.9
      Timeout: 30
      MemorySize: 256
      CodeUri: src/
      Handler: notifier.run
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          SLACK_BOT_TOKEN: !Ref SlackBotUserOAuthAccessToken
          SLACK_APP_ID: !Ref SlackAppId
          SLACK_CHANNEL: !Ref SlackChannel

      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'codepipeline:Get*'
                - 'codepipeline:List*'
              Resource: '*'
            - Effect: Allow
              Action:
                - 'codebuild:Get*'
              Resource: '*'
      Events:
        CodePipelineEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
              - aws.codepipeline
              - aws.codebuild
